server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  uploads-dir: ./uploads

aws:
  region: ap-south-1
  credentials:
    profile-name: default
  dynamodb:

    endpoint:

logging:
  level:
    root: INFO
    com.example.autoeval: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

